# Generated by Django 4.2.6 on 2023-10-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crudapp", "0002_userclass_remove_userinfo_email_userinfo_userclass"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userinfo",
            name="addresss",
        ),
        migrations.AddField(
            model_name="userinfo",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
